import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import { useContext } from 'react'
import Link from 'next/link'
import ArticleList from '@/components/ArticleList'

const inter = Inter({ subsets: ['latin'] })

export default function Home({ UserContext, posts }) {
  const { first_name, setUser } = useContext(UserContext);

  const handleLogoutClick = () => {
    localStorage.removeItem('jwt-token');
    setUser(null);
  }

  return (
    <>
      <Head>
        <title>Chug Blogs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=' flex flex-col justify-center items-center grow text-center [&>h1]:text-2xl [&>h1]:text-orange-700 [&>h1]:font-bold [&>h3]:text-gray-900'>
        {
          !first_name &&
            <>
              <h1>
                Chug Blogs
              </h1>

              <h3>
                Education, programming, KDrama, Anime, Life. <br />
                In front of a pint of beer.
              </h3>
            </>
        }

        {
          first_name && 
          <>
            <h1>Welcome, user {first_name}</h1>
            <h3>What do you want to do today?</h3>
            <ul className='flex flex-col gap-4 [&>li>button]:bg-slate-700 text-white [&>li>button]:px-6 [&>li>button]:py-3 [&>li>button]:rounded-full'>
                <li>
                    <button>
                      <Link href='/post/create'>Create A Post</Link>
                    </button>
                </li>

              <li><button onClick={handleLogoutClick}>Log Out</button></li>
            </ul>
          </>
        }

      </main>

      <section className='p-4 flex items-center flex-col sm:flex-row flex-wrap justify-center'>
        <ArticleList articles={posts} UserContext={UserContext}/>
      </section>
    </>
  )
}

export async function getServerSideProps() {
  const res = await fetch(`${process.env.NEXT_PUBLIC_SERVER}/api/post`);
  const posts = await res.json();

  return {
    props: {
      posts
    }
  }
}
