import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import { useContext } from 'react'
const inter = Inter({ subsets: ['latin'] })

export default function Home({ UserContext }) {
  const { first_name } = useContext(UserContext);

  return (
    <>
      <Head>
        <title>{first_name || 'Untitled'}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Welcome, user {first_name}.</h1>
        <h5>What do you want to do today?</h5>
      </main>
    </>
  )
}
