import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import { useContext } from 'react'
const inter = Inter({ subsets: ['latin'] })

export default function Home({ UserContext }) {
  const { first_name } = useContext(UserContext);

  return (
    <>
      <Head>
        <title>Chug Blogs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=' flex flex-col justify-center items-center grow text-center'>
        {
          !first_name &&
            <>
              <h1 className=' text-2xl text-orange-700 font-bold'>
                Chug Blogs
              </h1>

              <h3 className=' text-gray-900'>
                Education, programming, KDrama, Anime, Life. <br />
                In front of a pint of beer.
              </h3>
            </>
        }
      </main>
    </>
  )
}
